wandb_version: 1

save_folder:
  desc: null
  value: save/deneme1
trainset_path:
  desc: null
  value: ./train_dataset.pt
testset_path:
  desc: null
  value: ./validate_dataset.pt
device:
  desc: null
  value: cpu
model:
  desc: null
  value: cnmp
in_shape:
  desc: null
  value:
  - 7
  - 16
hidden_size:
  desc: null
  value: 256
num_hidden_layers:
  desc: null
  value: 2
weight_std:
  desc: null
  value: 1
min_std:
  desc: null
  value: 0.01
context_dims:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
target_dims:
  desc: null
  value:
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
max_context:
  desc: null
  value: 300
max_target:
  desc: null
  value: 300
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 20
max_iter:
  desc: null
  value: 200000
save_freq:
  desc: null
  value: 10000
test_freq:
  desc: null
  value: 10000
n_basis:
  desc: null
  value: 20
kernel_width:
  desc: null
  value: null
y_std:
  desc: null
  value: 0.1
amp:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683402860.458498
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.2
      8:
      - 5
